"""
Pyffice OBJ 3D Model Handler - Read/Write OBJ files
"""

from typing_extensions import Self
from pathlib import Path
from typing import List, Dict, Any, Tuple, Optional
from pyffice.document import PyfficeDocument


class PyfficeOBJ(PyfficeDocument):
    SERIALIZATION_VERSION = (1, 0, 0)
    EXTENSIONS = {".obj"}
    DEFAULT_LIMIT = 256 * 1024 * 1024  # 256MB

    def __init__(self, file_path: str) -> None:
        self.file_path = Path(file_path)
        self.vertices: List[Tuple[float, float, float]] = []
        self.normals: List[Tuple[float, float, float]] = []
        self.texcoords: List[Tuple[float, float]] = []
        self.faces: List[List[Tuple[int, int, int]]] = []  # vertex, texcoord, normal indices

    def read(self) -> Dict[str, Any]:
        """Read OBJ file and return structured data"""
        self.vertices = []
        self.normals = []
        self.texcoords = []
        self.faces = []

        with open(self.file_path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                parts = line.split()
                if not parts:
                    continue

                cmd = parts[0]
                if cmd == "v":
                    self.vertices.append((float(parts[1]), float(parts[2]), float(parts[3])))
                elif cmd == "vn":
                    self.normals.append((float(parts[1]), float(parts[2]), float(parts[3])))
                elif cmd == "vt":
                    self.texcoords.append((float(parts[1]), float(parts[2]) if len(parts) > 2 else 0))
                elif cmd == "f":
                    face = []
                    for vertex in parts[1:]:
                        indices = vertex.split("/")
                        vi = int(indices[0]) - 1 if indices[0] else 0
                        ti = int(indices[1]) - 1 if len(indices) > 1 and indices[1] else 0
                        ni = int(indices[2]) - 1 if len(indices) > 2 and indices[2] else 0
                        face.append((vi, ti, ni))
                    self.faces.append(face)

        return {"vertices": self.vertices, "normals": self.normals, "texcoords": self.texcoords, "faces": self.faces}

    def write(self, data: Dict[str, Any]) -> None:
        """Write data to OBJ file"""
        vertices = data.get("vertices", [])
        normals = data.get("normals", [])
        texcoords = data.get("texcoords", [])
        faces = data.get("faces", [])

        with open(self.file_path, "w") as f:
            f.write("# Generated by pyffice\n")

            for v in vertices:
                f.write(f"v {v[0]} {v[1]} {v[2]}\n")

            for vt in texcoords:
                f.write(f"vt {vt[0]} {vt[1]}\n")

            for vn in normals:
                f.write(f"vn {vn[0]} {vn[1]} {vn[2]}\n")

            for face in faces:
                face_str = "f"
                for vi, ti, ni in face:
                    face_str += f" {vi+1}/{ti+1 if ti is not None and ti < len(texcoords) else ''}/{ni+1 if ni is not None and ni < len(normals) else ''}"
                f.write(face_str + "\n")

    def load(self) -> Dict[str, Any]:
        """Alias for read()"""
        return self.read()

    def load_document(self, document=None) -> Self:
        logma.debug(f"{self.__class__.__name__}.load_document called")
        super().load_document(document)
        if not isinstance(document, dict):
            return self
        data = document.get("data", {}) or {}
        content = data.get("content", {}) or {}
        if isinstance(content, dict):
            if "file_path" in content:
                setattr(self, "file_path", content["file_path"])
            if "vertices" in content:
                setattr(self, "vertices", content["vertices"])
            if "normals" in content:
                setattr(self, "normals", content["normals"])
            if "texcoords" in content:
                setattr(self, "texcoords", content["texcoords"])
            if "faces" in content:
                setattr(self, "faces", content["faces"])
        return self

    def open_file(self, file_=None):
        import json as _json
        from os.path import exists
        if file_ is None:
            file_ = self.file_path
        if not file_ or not exists(file_):
            logma.warning(f"{self.__class__.__name__}.open_file: no such path {file_!r}")
            return self
        try:
            with open(file_, "r") as f:
                doc = _json.load(f)
        except (OSError, ValueError) as e:
            logma.warning(f"{self.__class__.__name__}.open_file failed for {file_!r}: {e}")
            return self
        return self.load_document(doc)

    def save(self, path=None, format_=None, encrypt=None):
        logma.debug(f"{self.__class__.__name__}.save called path={path!r}")
        super().save(path, format_, encrypt)
        if path is None:
            path = self.file_path
        if not path:
            logma.warning(f"{self.__class__.__name__}.save: no path available")
            return
        import json as _json
        doc = self.to_dict()
        with open(path, "w") as f:
            _json.dump(doc, f, indent=2, default=str)
        return

    def to_dict(self):
        logma.debug(f"{self.__class__.__name__}.to_dict called")
        super().to_dict()  # populate canonical envelope
        attrs = {
            "file_path": getattr(self, "file_path", None),
            "vertices": getattr(self, "vertices", None),
            "normals": getattr(self, "normals", None),
            "texcoords": getattr(self, "texcoords", None),
            "faces": getattr(self, "faces", None),
        }
        doc = {
            "did": self.did,
            "meta_data": {"schema_version": list(self.SERIALIZATION_VERSION)},
            "data": {
                "content": attrs,
                "document_type": "obj",
            },
        }
        return self._canonicalize(doc)


# Module-level convenience functions
def read(obj_path: str) -> Dict[str, Any]:
    """Read OBJ file"""
    return PyfficeOBJ(obj_path).read()


def load(obj_path: str) -> Dict[str, Any]:
    """Read OBJ file"""
    return read(obj_path)


def write(obj_path: str, data: Dict[str, Any]) -> None:
    """Write OBJ file"""
    PyfficeOBJ(obj_path).write(data)


__all__ = ["PyfficeOBJ", "read", "write", "load"]
