"""
Pyffice OBJ 3D Model Handler - Read/Write OBJ files
"""

from pathlib import Path
from typing import List, Dict, Any, Tuple, Optional
from pyffice.document import PyfficeDocument


class PyfficeOBJ(PyfficeDocument):
    SERIALIZATION_VERSION = (1, 0, 0)
    EXTENSIONS = {".obj"}
    DEFAULT_LIMIT = 256 * 1024 * 1024  # 256MB

    def __init__(self, file_path: str) -> None:
        self.file_path = Path(file_path)
        self.vertices: List[Tuple[float, float, float]] = []
        self.normals: List[Tuple[float, float, float]] = []
        self.texcoords: List[Tuple[float, float]] = []
        self.faces: List[List[Tuple[int, int, int]]] = []  # vertex, texcoord, normal indices

    def read(self) -> Dict[str, Any]:
        """Read OBJ file and return structured data"""
        self.vertices = []
        self.normals = []
        self.texcoords = []
        self.faces = []

        with open(self.file_path, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue

                parts = line.split()
                if not parts:
                    continue

                cmd = parts[0]
                if cmd == "v":
                    self.vertices.append((float(parts[1]), float(parts[2]), float(parts[3])))
                elif cmd == "vn":
                    self.normals.append((float(parts[1]), float(parts[2]), float(parts[3])))
                elif cmd == "vt":
                    self.texcoords.append((float(parts[1]), float(parts[2]) if len(parts) > 2 else 0))
                elif cmd == "f":
                    face = []
                    for vertex in parts[1:]:
                        indices = vertex.split("/")
                        vi = int(indices[0]) - 1 if indices[0] else 0
                        ti = int(indices[1]) - 1 if len(indices) > 1 and indices[1] else 0
                        ni = int(indices[2]) - 1 if len(indices) > 2 and indices[2] else 0
                        face.append((vi, ti, ni))
                    self.faces.append(face)

        return {"vertices": self.vertices, "normals": self.normals, "texcoords": self.texcoords, "faces": self.faces}

    def write(self, data: Dict[str, Any]) -> None:
        """Write data to OBJ file"""
        vertices = data.get("vertices", [])
        normals = data.get("normals", [])
        texcoords = data.get("texcoords", [])
        faces = data.get("faces", [])

        with open(self.file_path, "w") as f:
            f.write("# Generated by pyffice\n")

            for v in vertices:
                f.write(f"v {v[0]} {v[1]} {v[2]}\n")

            for vt in texcoords:
                f.write(f"vt {vt[0]} {vt[1]}\n")

            for vn in normals:
                f.write(f"vn {vn[0]} {vn[1]} {vn[2]}\n")

            for face in faces:
                face_str = "f"
                for vi, ti, ni in face:
                    face_str += f" {vi+1}/{ti+1 if ti is not None and ti < len(texcoords) else ''}/{ni+1 if ni is not None and ni < len(normals) else ''}"
                f.write(face_str + "\n")

    def load(self) -> Dict[str, Any]:
        """Alias for read()"""
        return self.read()

    def load_document(self, document=None) -> Self:
        """"""
        super().load_document(document)
        # TODO implement method
        return self

    def open_file(self, file_=None):
        """"""
        super().open_file(file_)
        # TODO implement method
        return self

    def save(self, path=None, format_=None, encrypt=None):
        """"""
        super().save(path, format_, encrypt)
        # TODO implement method
        return self

    def to_dict(self):
        # TODO implement method
        super().to_dict()
        return self


# Module-level convenience functions
def read(obj_path: str) -> Dict[str, Any]:
    """Read OBJ file"""
    return PyfficeOBJ(obj_path).read()


def load(obj_path: str) -> Dict[str, Any]:
    """Read OBJ file"""
    return read(obj_path)


def write(obj_path: str, data: Dict[str, Any]) -> None:
    """Write OBJ file"""
    PyfficeOBJ(obj_path).write(data)


__all__ = ["PyfficeOBJ", "read", "write", "load"]
