"""
Pyffice STL 3D Model Handler - Read/Write STL files (ASCII and Binary)
"""

from typing_extensions import Self
from pathlib import Path
from typing import List, Dict, Any, Tuple
import struct
import re

from pyffice.document import PyfficeDocument

from kahndor.logma import Logma

logma = Logma(__name__)
logma.off()


class PyfficeSTL(PyfficeDocument):
    SERIALIZATION_VERSION = (1, 0, 0)
    EXTENSIONS = {".stl"}
    DEFAULT_LIMIT = 256 * 1024 * 1024  # 256MB

    def __init__(self, file_path: str) -> None:
        self.file_path = Path(file_path)
        logma.debug(f"PyfficeSTL.__init__ called")
        self.faces: List[Dict[str, Any]] = []

    def read(self) -> Dict[str, Any]:
        """Read STL file (ASCII or binary)"""
        content = self.file_path.read_text(errors="ignore")

        if content.strip().startswith("solid"):
            # Try ASCII first
            self.faces = self._read_ascii(content)
            if not self.faces:
                # Might be binary with "solid" at start
                self.faces = self._read_binary()
        else:
            self.faces = self._read_binary()

        return {"faces": self.faces, "face_count": len(self.faces)}

    def _read_ascii(self, content: str) -> List[Dict[str, Any]]:
        """Parse ASCII STL"""
        faces = []
        # Match facet normal and vertex lines
        pattern = r"facet\s+normal\s+([\d.e+-]+)\s+([\d.e+-]+)\s+([\d.e+-]+)[\s\S]*?vertex\s+([\d.e+-]+)\s+([\d.e+-]+)\s+([\d.e+-]+)[\s\S]*?vertex\s+([\d.e+-]+)\s+([\d.e+-]+)\s+([\d.e+-]+)[\s\S]*?vertex\s+([\d.e+-]+)\s+([\d.e+-]+)\s+([\d.e+-]+)"

        for match in re.finditer(pattern, content):
            nx, ny, nz = float(match.group(1)), float(match.group(2)), float(match.group(3))
            v1 = (float(match.group(4)), float(match.group(5)), float(match.group(6)))
            v2 = (float(match.group(7)), float(match.group(8)), float(match.group(9)))
            v3 = (float(match.group(10)), float(match.group(11)), float(match.group(12)))
            faces.append({"normal": (nx, ny, nz), "vertices": [v1, v2, v3]})
        return faces

    def _read_binary(self) -> List[Dict[str, Any]]:
        """Parse binary STL"""
        faces = []
        with open(self.file_path, "rb") as f:
            # Skip 80-byte header
            f.read(80)
            # Read face count
            num_faces = struct.unpack("<I", f.read(4))[0]

            for _ in range(num_faces):
                data = f.read(50)  # 12 floats + 2 bytes
                normal = struct.unpack("<3f", data[:12])
                v1 = struct.unpack("<3f", data[12:24])
                v2 = struct.unpack("<3f", data[24:36])
                v3 = struct.unpack("<3f", data[36:48])
                faces.append({"normal": normal, "vertices": [v1, v2, v3]})
        return faces

    def write(self, data: Dict[str, Any], binary: bool = True) -> None:
        """Write STL file"""
        faces = data.get("faces", [])

        if binary:
            self._write_binary(faces)
        else:
            self._write_ascii(faces)

    def _write_binary(self, faces: List[Dict[str, Any]]) -> None:
        """Write binary STL"""
        with open(self.file_path, "wb") as f:
            # 80-byte header
            f.write(b"Generated by pyffice" + b"\0" * (80 - 20))
            # Face count
            f.write(struct.pack("<I", len(faces)))
            # Faces
            for face in faces:
                normal = face.get("normal", (0, 0, 1))
                vertices = face.get("vertices", [(0, 0, 0), (0, 0, 0), (0, 0, 0)])
                f.write(struct.pack("<3f", *normal))
                for v in vertices:
                    f.write(struct.pack("<3f", *v))
                f.write(struct.pack("<H", 0))  # Attribute byte count

    def _write_ascii(self, faces: List[Dict[str, Any]]) -> None:
        """Write ASCII STL"""
        with open(self.file_path, "w") as f:
            f.write("solid\n")
            for face in faces:
                normal = face.get("normal", (0, 0, 1))
                vertices = face.get("vertices", [])
                f.write(f"  facet normal {normal[0]} {normal[1]} {normal[2]}\n")
                f.write("    outer loop\n")
                for v in vertices:
                    f.write(f"      vertex {v[0]} {v[1]} {v[2]}\n")
                f.write("    endloop\n")
                f.write("  endfacet\n")
            f.write("endsolid\n")

    def load_document(self, document=None) -> Self:
        """"""
        super().load_document(document)
        # TODO implement method
        return self

    def open_file(self, file_=None):
        """"""
        super().open_file(file_)
        # TODO implement method
        return self

    def save(self, path=None, format_=None, encrypt=None):
        """"""
        super().save(path, format_, encrypt)
        # TODO implement method
        return self

    def to_dict(self):
        # TODO implement method
        super().to_dict()
        return self


# Module-level convenience functions
def read(stl_path: str) -> Dict[str, Any]:
    """Read STL file"""
    return PyfficeSTL(stl_path).read()


def load(stl_path: str) -> Dict[str, Any]:
    """Read STL file"""
    return read(stl_path)


def write(stl_path: str, data: Dict[str, Any], binary: bool = True) -> None:
    """Write STL file"""
    PyfficeSTL(stl_path).write(data, binary)


__all__ = ["PyfficeSTL", "read", "write", "load"]
